---
- name: Deploy the Anaible Tower Cluster Infrastructure
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  environment:
    OS_USERNAME: "{{ openstack_user }}"
    OS_PASSWORD: "{{ openstack_passwd }}"
    OS_AUTH_URL: http://{{ openstack_ip }}:5000/v3
    OS_PROJECT_NAME: "{{ openstack_project }}"
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_IDENTITY_API_VERSION: 3

  tasks:
  - import_role:
      name: osp-stack-create
  - import_role:
      name: osp-inventory
    tags: ['inv']

- name: Prepare Ansible Tower Nodes
  hosts: cluster
  become: true
  gather_facts: true

  tasks:
  - import_role:
      name: tower-prep
    tags: ['prep']

- name: Install Ansible Tower
  hosts: tower
  become: true
  gather_facts: true

  tasks:
  - import_role:
      name: tower-install
    tags: ['install']
