- name: Copy hosts file from template
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: check if host already registered
  command: subscription-manager list --available --match-installed --matches=*RHEL* --pool-only
  register: subs_result
  failed_when: false
  changed_when: "'This system is not yet registered' in subs_result.stderr"

- name: Check Red Hat subscription using username
  redhat_subscription:
    state: present
    username: "{{ rhn_username_or_org_id }}"
    password: "{{ rhn_password_or_activation_key }}"
    pool: "{{ rhn_pool }}"
    #force_register: yes
  register: subscribe_user
  retries: 5
  delay: 5
  when: subscription_use_username == True and subs_result.changed

- name: Check Red Hat subscription using activation key
  redhat_subscription:
    state: present
    org_id: "{{ rhn_username_or_org_id }}"
    activationkey: "{{ rhn_password_or_activation_key }}"
    pool: "{{ rhn_pool }}"
    #force_register: yes
  register: subscribe_activation_key
  retries: 5
  delay: 5
  when: subscription_use_username == False and subs_result.changed

- debug:
    msg: "username subscription {{ subscribe_user.changed }}"

- debug:
    msg: "activation key subscription {{ subscribe_activation_key.changed }}"

- name: Disable all repos
  shell: |
    subscription-manager repos --disable=*
  retries: 5
  delay: 5
  when: subscribe.changed

- name: Enable correct repos
  command: "subscription-manager repos --enable={{item}}"
  when: subscribe.changed
  retries: 5
  delay: 5
  with_items: "{{repos}}"

- name: Upgrade packages
  yum:
    name: '*'
    state: latest

- name: Install required packages
  yum:
    name: "{{item}}"
    state: latest
  retries: 5
  delay: 5
  with_items: "{{packages}}"

- name: Setup ssh authentication for {{ ssh_user }}
  lineinfile:
    dest: /etc/sudoers.d/{{ ssh_user }}
    line: "{{ ssh_user }} ALL=(ALL) NOPASSWD: ALL"
    insertbefore: BOF
    create: yes
    state: present

- name: Get SSH Key for user {{ ssh_user }}
  fetch:
    src: /home/{{ ssh_user }}/.ssh/id_rsa.pub
    dest: ~/

- name: Add key to authorized keys for user {{ ssh_user }}
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('file', '~/{{ inventory_hostname }}/home/{{ ssh_user }}/.ssh/id_rsa.pub') }}"
